- name: mysql configuratin
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present
    
  - name: start services
    ansible.builtin.service:
      name: mysqld
      state: started
      